name: GitHub Actions

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [23.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm test
            - run: npm run lint
              env:
                  API_KEY: ${{secrets.API_KEY}}
                  API_KEY2: ${{secrets.API_KEY2}}
            - name: Test Report
              uses: dorny/test-reporter@v1
              with:
                  name: unit tests (${{ matrix.node-version }})
                  path: test-results.json
                  reporter: mocha-json

            - name: Output logs if failure
              if: failure()
              run: |
                  echo "=== NPM Debug Log ==="
                  ls
                  cat test-results.json || true
